INSERT INTO SKILLS (skill) VALUES('Drooling')
INSERT INTO SKILLS (skill) VALUES('Driving')
INSERT INTO SKILLS (skill) VALUES('Efficiency expert')
INSERT INTO SKILLS (skill) VALUES('Comendering')
INSERT INTO SKILLS (skill) VALUES('Pirating')
INSERT INTO SKILLS (skill) VALUES('Dependency Injection')
INSERT INTO SKILLS (SKILL) VALUES('Cuddling')
INSERT INTO SKILLS (skill) VALUES('Gravity Testing')
INSERT INTO SKILLS (skill) VALUES('Filling Boxes')
INSERT INTO SKILLS (skill) VALUES('Hate')
INSERT INTO SKILLS (skill) VALUES('Schedule Management')
INSERT INTO SKILLS (skill) VALUES('Hiding')
INSERT INTO SKILLS (skill) VALUES('Life Coach')
--INSERT INTO SKILLS (skill) VALUES('')

INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Percy','orange $ white', 'Long', 12, 'Purficient at wakeup calls', 'Percy.jpg', 1 )
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Fern', 'tabby', 'long', 8, 'Will do anything for bread.', 'fern.jpg', 0 )
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Luna', 'Black & Orange', 'short', 3, 'Flexible for the right opportunity', 'luna.jpg', 0 )
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Picard', 'orange', 'short', 7, 'Licking, Stealing food, Commanding USS Enterprise', 'picard.jpg', 0)
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Memesiku', 'calico', 'long', 9, 'Flooping, Drooling, Hunting gnats', 'memsiku.jpg', 1 )
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Wulfgang', 'black', 'long', 7, 'Always looking for new ways to assinate dogs', 'wulfgang.jpg', 0 )
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Brahm', 'brown', 'short', 5, '100% good boy 0% cat', 'brahm.jpg', 0)
--INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('', '',, '', '', 0)
