--DELETE FROM Skill
INSERT INTO Skills (skill) VALUES('Drooling')
INSERT INTO Skills (skill) VALUES('Driving')
INSERT INTO Skills (skill) VALUES('Efficiency expert')
INSERT INTO Skills (skill) VALUES('Comendering')
INSERT INTO Skills (skill) VALUES('Pirating')
INSERT INTO Skills (skill) VALUES('Dependency Injection')
INSERT INTO Skills (SKILL) VALUES('Cuddling')
INSERT INTO Skills (skill) VALUES('Gravity Testing')
INSERT INTO Skills (skill) VALUES('Filling Boxes')
INSERT INTO Skills (skill) VALUES('Hate')
INSERT INTO Skills (skill) VALUES('Schedule Management')
INSERT INTO Skills (skill) VALUES('Hiding')
INSERT INTO Skills (skill) VALUES('Life Coach')
--INSERT INTO SKILLS (skill) VALUES('')

--DELETE FROM Cats
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Percy',		'orange $ white', 'Long',  12, 'Purficient at wakeup calls',						'Percy.jpg',	1, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Fern',		'tabby',		  'long',   8, 'Will do anything for bread.',						'fern.jpg',		0, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Luna',		'Black & Orange', 'short',  3, 'Flexible for the right opportunity',				'luna.jpg',		0, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Picard',		'orange',		  'short',  7, 'Licking, Stealing food, Commanding USS Enterprise', 'picard.jpg',	0, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Memesiku',	'calico',		  'long',   9, 'Flooping, Drooling, Hunting gnats',					'memsiku.jpg',	1, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Wulfgang',	'black',		  'long',   7, 'Always looking for new ways to assinate dogs',		'wulfgang.jpg', 0, '')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured, description ) VALUES ('Brahm',		'brown',		  'short',  5, '100% good boy 0% cat',								'brahm.jpg',	0, '')
--INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('', '',, '', '', 0 ,'')

--DELETE FROM cat_skill
INSERT INTO cat_skill (cat_id, skill_id) VALUES(1, 1)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(1, 7)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(2, 6)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(2, 10)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(3, 2)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(3, 5)
INSERT INTO cat_skill (cat_id, skill_id) VALUES(3, 9)
--INSERT INTO cat_skill (cat_id, skill_id) VALUES(, )

--DELETE  FROM Users
INSERT INTO Users (name, email, password, is_admin) VALUES ('Dinah',			'djmorrisj@email.com',			'password', 1)
INSERT INTO Users (name, email, password, is_admin) VALUES ('Peter',			'codesmore@yahoo.com',			'password', 1)
INSERT INTO Users (name, email, password, is_admin) VALUES ('Dan',				'danieltalik@gmail.com',		'password', 1)
INSERT INTO Users (name, email, password, is_admin) VALUES ('Austin',			'austin.wxj@gmail.com',			'password', 1)
INSERT INTO Users (name, email, password, is_admin) VALUES ('John',				'john@techelevator.com',		'password', 1)
INSERT INTO Users (name, email, password, is_admin) VALUES ('Babadook',			'babadook@email.com',			'password', 0)
INSERT INTO Users (name, email, password, is_admin) VALUES ('rumpelstiltskin',	'rumpdahump@email.com',			'password', 0)
INSERT INTO Users (name, email, password, is_admin) VALUES ('Slenderman',		'slendy@email.com',				'password', 0)
INSERT INTO Users (name, email, password, is_admin) VALUES ('NightMan',			'EnemyofDayman@email.com',		'password', 0)
INSERT INTO Users (name, email, password, is_admin) VALUES ('DayMan',			'FighterofNightman@email.com',  'password', 0)
--INSERT INTO Users (name, password, is_admin) VALUES ('', '', 0)

