INSERT INTO SKILLS (skill) VALUES('Drooling')
INSERT INTO SKILLS (skill) VALUES('Driving')
INSERT INTO SKILLS (skill) VALUES('Efficiency expert')
INSERT INTO SKILLS (skill) VALUES('Comendering')
INSERT INTO SKILLS (skill) VALUES('Pirating')
INSERT INTO SKILLS (skill) VALUES('Dependency Injection')
INSERT INTO SKILLS (SKILL) VALUES('Cuddling')
INSERT INTO SKILLS (skill) VALUES('Gravity Testing')
INSERT INTO SKILLS (skill) VALUES('Filling Boxes')
INSERT INTO SKILLS (skill) VALUES('Hate')
INSERT INTO SKILLS (skill) VALUES('Schedule Management')
INSERT INTO SKILLS (skill) VALUES('Hiding')
INSERT INTO SKILLS (skill) VALUES('Life Coach')
--INSERT INTO SKILLS (skill) VALUES('')

INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Percy')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Fern')
INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ('Luna')
--INSERT INTO Cats (name, color, hair_length, age, prior_exp, photo, is_featured ) VALUES ()
